/*
 * Braking_System_2.h
 *
 *  Created on: Aug 27, 2024
 *      Author: Micropolis
 */

#ifndef INC_BRAKING_SYSTEM_2_H_
#define INC_BRAKING_SYSTEM_2_H_

#include "stdlib.h"

#define BRAKE_APPLY_MAX_SPEED			-80.0
#define BRAKE_RELEASE_MAX_SPEED			80.0

#define BRAKE_SPEED		80.0
#define BRAKE_SPEED_ZERO		0.0

/* Brake Limit Switch Number */
#define BRAKE_LS_START		4
#define BRAKE_LS_END		5

#define BRAKE_SPEED_CHANGE_VALUE		10.0

typedef enum
{
	BRAKE_COMMAND_OFF,
	BRAKE_COMMAND_APPLY,
	BRAKE_COMMAND_RELEASE,
	BRAKE_COMMAND_CALIB,
	BRAKE_CONTINUOUS_RUN,
	BRAKE_COMMAND_INVALID = 0xFF
}BrakeCommand_t;

typedef enum
{
	BRAKE_STATUS_OFF,
	BRAKE_STATUS_BRAKING,
	BRAKE_STATUS_FULL_BRAKE,
	BRAKE_STATUS_RELEASING,
	BRAKE_STATUS_FULL_RELEASE,
	BRAKE_STATUS_CUBEMARS_STOP,
	BRAKE_STATUS_CAN_DISABLE,
	BRAKE_STATUS_LIMIT_ERROR,
	BRAKE_STATUS_INVALID = 0xFF
}BrakeStatus_t;

typedef enum
{
	BRAKE_CALIB_NOT_STARTED,
	BRAKE_CALIB_STARTED,
	BRAKE_CALIB_BRAKING,
	BRAKE_CALIB_FULL_BRAKE,
	BRAKE_CALIB_RELEASING,
	BRAKE_CALIB_FULL_RELEASE,
	BRAKE_CALIB_FINISHED_SUCCESSFULLY,
	BRAKE_CALIB_ERROR,
	BRAKE_CALIB_STATE_INVALID = 0xFF
}Brake_Calib_State_t;


#endif /* INC_BRAKING_SYSTEM_2_H_ */
