/*
 * Lifter_M01.h
 *
 *  Created on: Aug 7, 2024
 *      Author: Micropolis
 */

#ifndef INC_LIFTER_M01_H_
#define INC_LIFTER_M01_H_

#include "CubeMars.h"
#include "PositionSensor.h"

#define LIFT_SPEED		-80.0
#define UNLIFT_SPEED	80.0

#define LIFTER_TASK_CYCLE_TIME		5
#define CURRENT_BRAKE_TIMEOUT		2000

typedef enum
{
	LIFTER_MODE_LIMITSWITCH,
	LIFTER_MODE_POSITION,
	LIFTER_MODE_INVALID = 0xFF
}LifterMode_t;
typedef enum
{
	LIFTER_COMMAND_OFF,
	LIFTER_COMMAND_LIFT,
	LIFTER_COMMAND_UNLIFT,
	LIFTER_COMMAND_POS_CALIB,
	LIFTER_CONTINUOUS_RUN,
	LIFTER_COMMAND_INVALID = 0xFF
}LifterCommand_t;

typedef enum
{
	LIFTER_STATUS_OFF,
	LIFTER_STATUS_LIFTING,
	LIFTER_STATUS_LIFTED,
	LIFTER_STATUS_UNLIFTING,
	LIFTER_STATUS_UNLIFTED,
	LIFTER_STATUS_BRAKING,
	LIFTER_STATUS_CAN_DISABLE,
	LIFTER_STATUS_LIMIT_ERROR,
	LIFTER_STATUS_INVALID = 0xFF
}LifterStatus_t;

typedef enum
{
	CALIB_NOT_STARTED,
	CALIB_STARTED,
	CALIB_LIFTING,
	CALIB_LIFTED,
	CALIB_UNLIFTING,
	CALIB_UNLIFTED,
	CALIB_FINISHED_SUCCESSFULLY,
	CALIB_ERROR,
	CALIB_STATE_INVALID = 0xFF
}Calib_State_t;
void Lifter_M01_Loop();


#endif /* INC_LIFTER_M01_H_ */
